Detect monitors by size to load correct autorandr
My binding `$mod+n $mod+Shift+d`, which attempts to force awaken
my Dell monitor and then spread my desktop across the two displays,
wasn't working reliably this morning.

I saw that the `autorandr docked` config was referencing a display
(DP-0) which `xrandr -q` was reporting as disconnected. DP-0 in the
docked config intends to reference the laptop display, which as of
this moment is actually being detected by xrandr as DP-2, not DP-0.

Now we detect the monitors' display values by finding their physical
sizes in the `xrandr q` output, and then load the correct autorandr
profile.

----

For this to work requires having a bunch of different autorandr
profiles. (I tried ditching autorandr for raw xrandr but autorandr
seems to poke the Dell awake in a way that xrandr does not.)

I've added convenience mobile/docked toggles to this command to
mimic the `autorandr {docked,mobile}' interaction which I'm losing.

diff --git a/bin/i3-autorandr b/bin/i3-autorandr
--- a/bin/i3-autorandr
+++ b/bin/i3-autorandr
@@ -2,6 +2,54 @@
 
 # try hard to force my external monitor on when I come back from idle
 
-xset dpms force on
-sleep .25
-autorandr docked || sleep .25 && autorandr docked
+function i3::autorandr::docked() {
+
+  # The monitors hop around with how xrandr identifies them, which I don't understand. Here's
+  # what I've seen:
+  #
+  #   Dell     Laptop   Notes
+  #   ----     ------   ------
+  #   DP-1     DP-0     Fresh login
+  #   DP-1     DP-2     Displays idle ~30 min and then reawaken
+  #   DP-1     eDP-1    Mid-upgrade, using open-source drivers; switching to nvidia drivers fixed it
+  #
+  # I have no idea why the laptop display bounces around. The physical dimensions only
+  # shows up if the monitor is actually being used, so Dell is "the connected monitor
+  # whose display isn't the size of the laptop's display".
+  #
+  local dell=$(xrandr | grep ' connected' | grep -v '344mm x 194mm' | cut -f 1 -d ' ' | tr 'A-Z' 'a-z')
+  local laptop=$(xrandr | grep '344mm x 194mm' | cut -f 1 -d ' ' | tr 'A-Z' 'a-z')
+
+  # this relies on having an autorandr config already saved
+
+  case "$dell,$laptop" in
+    "dp-1,dp-0" )
+      autorandr docked;
+      return $?;
+      ;;
+    "dp-1,dp-2" )
+      autorandr docked-$dell,$laptop;
+      return $?;
+      ;;
+    *)
+      echo "error: dell $dell, laptop $laptop, no profile to use!" 1>&2;
+      return 1
+      ;;
+  esac
+
+}
+
+action=${1:-docked}; shift
+case $action in
+  docked )
+    xset dpms force on;
+    sleep .25;
+    i3::autorandr::docked || sleep .25 && i3::autorandr::docked;
+    ;;
+  mobile )
+    autorandr mobile;
+    ;;
+  * )
+    echo "Usage: i3-autorandr [mobile | docked]" 1>&2;
+    ;;
+esac
