Use i3-nagbar to present errors
No clue where i3's log is. Just use the nagbar to inform me that
something didn't work as planned.

----

Also, make sure the autorandr profile we try to load corresponds
to one which I've actually saved! This previously failed because
I had a saved profile in autorandr named

    docked-dp1,dp2

but was trying to load

    docked-dp-1,dp-2

The display names from `xrandr` have a hyphen in them which I
needed to accomodate somehow.

I fixed it within autorandr by re-saving my config to be
named

    docked:dp-1,dp-2

(i.e. allow hyphens, and change the delimiter to a colon so the
hyphen isn't overloaded)

Tweak the script a little to handle the new delimiter.

diff --git a/bin/i3-autorandr b/bin/i3-autorandr
--- a/bin/i3-autorandr
+++ b/bin/i3-autorandr
@@ -28,12 +28,12 @@ function i3::autorandr::docked() {
       return $?;
       ;;
     "dp-1,dp-2" )
-      autorandr docked-$dell,$laptop;
+      autorandr docked:$dell,$laptop;
       return $?;
       ;;
     *)
-      echo "error: dell $dell, laptop $laptop, no profile to use!" 1>&2;
-      return 1
+      i3-nagbar -t error -m "error: i3-autorandr can't fix display: dell $dell, laptop $laptop, no profile to use!" -B 'let me fix it' 'i3-sensible-terminal';
+      exit 1
       ;;
   esac
 
